# You can add key value pair here, to create env values.
# for example,

# ENV: dev
SERVICE_ENVIRONMENT: "{{ .Values.global.environment }}" 
LOG_LEVEL: "{{ .Values.log_level }}" 
CONFIG_INI_PATH: "{{ .Values.config_ini_path }}" 
OPENAI_TYPE: "{{ .Values.global.openai_type }}" 
OPENAI_API_BASE: "{{ .Values.global.openai_api_base }}" 
OPENAI_API_VERSION: "{{ .Values.global.openai_api_version }}" 
OPENAI_API_KEY: "{{ .Values.global.openai_api_key }}" 
GPT_MODEL: "{{ .Values.global.gpt_model }}" 
TRANSLATION_TYPE: "{{ .Values.global.translation_type }}" 
BHASHINI_ENDPOINT_URL: "{{ .Values.global.bhasini_endpoint_url }}" 
BHASHINI_API_KEY: "{{ .Values.global.bhasini_api_key }}" 
GCP_CONFIG_PATH: "{{ .Values.gcp_config_path }}" 
BUCKET_TYPE: "{{ .Values.global.bucket_type }}" 
BUCKET_ENDPOINT_URL: "{{ .Values.global.bucket_endpoint_url }}" 
BUCKET_REGION_NAME: "{{ .Values.global.bucket_region_name }}" 
BUCKET_NAME: "{{ .Values.global.bucket_name }}" 
BUCKET_SECRET_ACCESS_KEY: "{{ .Values.global.bucket_secret_key }}" 
BUCKET_ACCESS_KEY_ID: "{{ .Values.global.bucket_access_key }}" 
MARQO_URL: "{{ .Values.global.marqo_url }}" 
TELEMETRY_ENDPOINT_URl: "{{ .Values.telemetry_url }}" 
TELEMETRY_LOG_ENABLED: "{{ .Values.telemetry_log_enabled }}" 



