{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/*" }} 
  {{- if ne $path "configs/env.yaml" }} 
    {{ base $path | nindent 2 }}: |-
      {{- with $currentScope }}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
